### ISSUE TITLE
no omnipro.jar

### ISSUE THREAD

**Issue by Borval99** [Matodak/omnilink#1]
there is no omnipro.jar file, what i can do?

**Comment by Borval99** [comment]
> there is no omnipro.jar file, what i can do?

omnilink.jar sorry *

**Comment by martin-leclerc** [comment]
You need to build it yourself. See readme file for details.

**Comment by Borval99** [comment]
@ECHO OFF

REM === Set the location of the SDK ===
IF NOT "%JAVA_HOME%" == "" GOTO init
SET JAVA_HOME=C:\jdk1.6.0_12

:init
REM === Root directory of this product ===
SET PRODUCT_HOME=..\..\..\

REM === Make sure all the files are properly installed ===
IF NOT EXIST %JAVA_HOME%\bin\javac.exe GOTO nojavac
IF NOT EXIST %JAVA_HOME%\bin\java.exe GOTO nojava
IF NOT EXIST %JAVA_HOME%\jre\bin\rxtxSerial.dll GOTO nodll
IF NOT EXIST %JAVA_HOME%\jre\lib\ext\RXTXcomm.jar GOTO norxtx
IF NOT EXIST %PRODUCT_HOME%\lib\omnilink.jar GOTO nolib

REM === Set the CLASSPATH ===
SET CLASS_PATH=%PRODUCT_HOME%\lib\omnilink.jar

REM === Compile the console code ===
%JAVA_HOME%\bin\javac -classpath %CLASS_PATH% MessageFactory.java Console.java NetworkMain.java

REM === Execute the console ====
%JAVA_HOME%\bin\java -classpath .;%CLASS_PATH% NetworkMain

GOTO END

:nojavac
ECHO Error: %JAVA_HOME%\bin\javac.exe not found
GOTO END

:nojava
ECHO Error: %JAVA_HOME%\bin\java.exe not found
GOTO END

:nodll
ECHO Error: %JAVA_HOME%\jre\bin\rxtxSerial.dll not found
GOTO END

:norxtx
ECHO Error: %JAVA_HOME%\jre\lib\ext\RXTXcomm.jar not found
GOTO END

:nolib
ECHO Error: %PRODUCT_HOME%\lib\omnilink.jar not found
GOTO END

:END
SET PRODUCT_HOME=
SET CLASS_PATH=


that is your test program, i tested it, it give me back that error: omnilink.jar not found

**Comment by Borval99** [comment]
I have this product, from the HAI, it works with your java project?
https://www.leviton.com/en/products/20a00-21

**Comment by Borval99** [comment]
i have fixed my jdk, now it work! 
when i try to start a connection, it report:
Controller reports that the client session is not active or session IDs are not identical
How i can fix this?

**Comment by Borval99** [comment]
HEY? can you help me please?

**Comment by Borval99** [comment]
i m stuck on this error!
